# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CV | Dmytro Rudnytskykh
description: > # this means to ignore newlines until "baseurl:"
  Frontend developer with 4 years experience. I love to create stunning user-friendly interfaces, write maintainable code and help business create effective solutions. Have experience implementing complex UI business logic, writing tests, creating and supporting markup with 100 and more pages, advanced experience in responsive design, working in a big multinational team.
baseurl: ""
url: "http://rudnitskih.pp.ua" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-68863446-1
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
